import type { Product } from "@/types/product"

export const mockProducts: Product[] = [
  // Women's Dresses
  {
    id: "w1",
    name: "Elegant Black Evening Gown",
    description:
      "A stunning floor-length black evening gown with intricate beadwork and a flowing silhouette. Perfect for galas, weddings, and formal events.",
    price: 459.99,
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Burgundy"],
    images: ["https://www.newyorkdress.com/cdn/shop/products/Ladivine-CDS450_black_600x.jpg?v=1745422743"],
    inStock: true,
    featured: true,
    carbonFootprint: 12.5,
    isEcoVerified: false,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "w2",
    name: "Classic Cocktail Dress",
    description:
      "Timeless cocktail dress with a fitted bodice and A-line skirt. Features a subtle shimmer fabric that catches the light beautifully.",
    price: 229.99,
    category: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "White", "Red", "Navy"],
    images: ["https://www.newyorkdress.com/cdn/shop/products/CD0187_rosegold_1_18fcbc1a-b22a-4b9f-a25f-eaf05f184d98-660593_600x.jpg?v=1681464209"],
    inStock: true,
    featured: false,
    carbonFootprint: 8.3,
    isEcoVerified: false,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "w3",
    name: "Bohemian Maxi Dress",
    description:
      "Free-spirited maxi dress with flowing fabric, floral patterns, and bell sleeves. Perfect for summer festivals and casual elegance.",
    price: 159.99,
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Floral Print", "Solid Navy", "Burgundy"],
    images: ["https://image.hm.com/assets/hm/9f/22/9f22534792e9433a63803799f9d15b6865733012.jpg?imwidth=564"],
    inStock: true,
    featured: true,
    carbonFootprint: 6.7,
    carbonCertificate: "/certificates/bohemian-maxi-cert.pdf",
    isEcoVerified: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "w4",
    name: "Professional Sheath Dress",
    description:
      "Sophisticated sheath dress perfect for the office or business meetings. Clean lines and premium fabric ensure a polished look.",
    price: 189.99,
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Gray", "Burgundy"],
    images: ["https://www.alamodelabel.in/cdn/shop/files/22FE5E11-CF05-4561-9484-1E1DFFDC9C50_600x.jpg?v=1749206058"],
    inStock: true,
    featured: false,
    carbonFootprint: 7.2,
    carbonCertificate: "/certificates/professional-sheath-cert.pdf",
    isEcoVerified: true,
    createdAt: new Date("2024-01-25"),
  },
  {
    id: "w5",
    name: "Vintage Tea Dress",
    description:
      "Charming vintage-inspired tea dress with a cinched waist and midi length. Features delicate lace details and button-front closure.",
    price: 139.99,
    category: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Cream", "Dusty Rose", "Sage Green"],
    images: ["https://m.media-amazon.com/images/I/614dz0E+fWL.jpg"],
    inStock: true,
    featured: false,
    carbonFootprint: 5.8,
    carbonCertificate: "/certificates/vintage-tea-cert.pdf",
    isEcoVerified: true,
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "w6",
    name: "Designer Ball Gown",
    description:
      "Luxurious ball gown with a full skirt, fitted bodice, and exquisite embroidery. Made from premium silk and tulle for special occasions.",
    price: 899.99,
    category: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Ivory", "Blush Pink", "Champagne"],
    images: ["https://img.perniaspopupshop.com/catalog/product/d/l/DLLC082461_1.jpg?impolicy=detailimageprod"],
    inStock: true,
    featured: true,
    carbonFootprint: 18.9,
    isEcoVerified: false,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "w7",
    name: "Summer Sundress",
    description:
      "Light and breezy sundress perfect for warm weather. Features adjustable straps and a comfortable fit-and-flare silhouette.",
    price: 79.99,
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Yellow", "Coral", "White", "Light Blue"],
    images: ["https://img.perniaspopupshop.com/catalog/product/d/v/DVNC032528_1.jpeg?impolicy=detailimageprod"],
    inStock: true,
    featured: false,
    carbonFootprint: 4.2,
    carbonCertificate: "/certificates/summer-sundress-cert.pdf",
    isEcoVerified: true,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "w8",
    name: "Wrap Midi Dress",
    description:
      "Versatile wrap dress with a flattering midi length. The adjustable tie waist creates a perfect silhouette for any body type.",
    price: 119.99,
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Emerald", "Burgundy"],
    images: ["https://img.perniaspopupshop.com/catalog/product/g/a/GANC052502_1.jpg?impolicy=detailimageprod"],
    inStock: true,
    featured: false,
    carbonFootprint: 6.1,
    carbonCertificate: "/certificates/wrap-midi-cert.pdf",
    isEcoVerified: true,
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "w9",
    name: "Lace Bodycon Dress",
    description:
      "Elegant lace bodycon dress that hugs your curves perfectly. Features intricate lace overlay and a comfortable stretch lining.",
    price: 169.99,
    category: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "White", "Nude", "Navy"],
    images: ["https://img.perniaspopupshop.com/catalog/product/i/k/IKCI042320_1.jpg?ImPolicy=listingimagedesktop"],
    inStock: true,
    featured: false,
    carbonFootprint: 7.8,
    isEcoVerified: false,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "w10",
    name: "Off-Shoulder Party Dress",
    description:
      "Glamorous off-shoulder party dress with sequin details and a fit-and-flare silhouette. Perfect for celebrations and night out.",
    price: 199.99,
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Gold", "Silver", "Rose Gold", "Black"],
    images: ["https://img.perniaspopupshop.com/catalog/product/r/h/RHRI062522_1.jpg?ImPolicy=listingimagedesktop"],
    inStock: true,
    featured: true,
    carbonFootprint: 9.4,
    isEcoVerified: false,
    createdAt: new Date("2024-02-25"),
  },

  // Men's Dresses
  {
    id: "m1",
    name: "Classic Tuxedo Dress",
    description:
      "Sophisticated tuxedo-style dress with sharp tailoring and satin lapels. Perfect for formal events and black-tie occasions.",
    price: 549.99,
    category: "men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Charcoal"],
    images: ["https://img.perniaspopupshop.com/catalog/product/j/m/jmcc092292.jpg?ImPolicy=listingimagedesktop"],
    inStock: true,
    featured: true,
    carbonFootprint: 15.2,
    isEcoVerified: false,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "m2",
    name: "Traditional Kaftan",
    description:
      "Elegant traditional kaftan with modern tailoring. Features intricate embroidery and a comfortable, flowing fit.",
    price: 189.99,
    category: "men",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["White", "Cream", "Light Gray", "Navy"],
    images: ["https://images-na.ssl-images-amazon.com/images/I/3101qqXO81L.jpg"],
    inStock: true,
    featured: false,
    carbonFootprint: 8.7,
    isEcoVerified: false,
    createdAt: new Date("2024-01-25"),
  },
  {
    id: "m3",
    name: "Modern Thobe Dress",
    description:
      "Contemporary thobe with clean lines and premium fabric. Combines traditional style with modern comfort and elegance.",
    price: 159.99,
    category: "men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Beige", "Gray"],
    images: ["https://m.media-amazon.com/images/I/51d42pWwjvL._AC_UL320_.jpg"],
    inStock: true,
    featured: true,
    carbonFootprint: 7.3,
    carbonCertificate: "/certificates/modern-thobe-cert.pdf",
    isEcoVerified: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "m4",
    name: "Formal Robe Dress",
    description:
      "Luxurious formal robe dress with silk lining and elegant draping. Perfect for ceremonial occasions and special events.",
    price: 399.99,
    category: "men",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Deep Purple", "Burgundy", "Forest Green", "Navy"],
    images: ["https://cdn.shopify.com/s/files/1/0114/5264/5476/products/IMG_2326_540x.jpg?v=1653843724"],
    inStock: true,
    featured: false,
    carbonFootprint: 12.8,
    isEcoVerified: false,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "m5",
    name: "Casual Tunic Dress",
    description:
      "Comfortable tunic dress perfect for casual occasions. Features a relaxed fit and breathable cotton blend fabric.",
    price: 89.99,
    category: "men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Khaki", "Navy", "Olive", "Charcoal"],
    images: ["https://images.meesho.com/images/products/71112418/uj8p7_1200.jpg"],
    inStock: true,
    featured: false,
    carbonFootprint: 5.1,
    carbonCertificate: "/certificates/casual-tunic-cert.pdf",
    isEcoVerified: true,
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "m6",
    name: "Designer Kurta Dress",
    description:
      "Exquisite designer kurta with hand-embroidered details and premium silk fabric. A masterpiece of traditional craftsmanship.",
    price: 299.99,
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Ivory", "Gold", "Maroon", "Royal Blue"],
    images: ["https://m.media-amazon.com/images/I/516W1fHU5sL.jpg"],
    inStock: true,
    featured: true,
    carbonFootprint: 11.6,
    isEcoVerified: false,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "m7",
    name: "Minimalist Long Dress",
    description:
      "Clean, minimalist long dress with contemporary styling. Perfect for modern men who appreciate understated elegance.",
    price: 179.99,
    category: "men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Gray", "Camel"],
    images: ["https://www.beigebrown.com/cdn/shop/files/BB-blog_minwardrobe_1_600x.jpg?v=1709290220"],
    inStock: true,
    featured: false,
    carbonFootprint: 6.9,
    carbonCertificate: "/certificates/minimalist-long-cert.pdf",
    isEcoVerified: true,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "m8",
    name: "Ceremonial Dress Robe",
    description:
      "Majestic ceremonial dress robe with gold trim and intricate patterns. Designed for special ceremonies and cultural events.",
    price: 459.99,
    category: "men",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Royal Blue", "Deep Red", "Emerald", "Black"],
    images: ["https://m.media-amazon.com/images/I/51Hj9LHKtwL.jpg"],
    inStock: true,
    featured: true,
    carbonFootprint: 14.3,
    isEcoVerified: false,
    createdAt: new Date("2024-01-30"),
  },
  {
    id: "m9",
    name: "Linen Summer Dress",
    description:
      "Lightweight linen dress perfect for warm weather. Features a comfortable loose fit and natural breathability.",
    price: 129.99,
    category: "men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Natural", "Light Blue", "Sage", "Stone"],
    images: ["https://i.etsystatic.com/34008231/r/il/2c6c29/4919914323/il_fullxfull.4919914323_db1p.jpg"],
    inStock: true,
    featured: false,
    carbonFootprint: 4.8,
    carbonCertificate: "/certificates/linen-summer-cert.pdf",
    isEcoVerified: true,
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "m10",
    name: "Evening Formal Dress",
    description:
      "Sophisticated evening formal dress with velvet accents and tailored fit. Perfect for upscale dinner parties and galas.",
    price: 349.99,
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Midnight Blue", "Burgundy", "Charcoal"],
    images: ["https://static.wixstatic.com/media/232e4c_dacd5105c8ac4526a77694048618928d~mv2.jpg/v1/fill/w_564,h_1206,al_c,q_85,enc_avif,quality_auto/232e4c_dacd5105c8ac4526a77694048618928d~mv2.jpg"],
    inStock: true,
    featured: false,
    carbonFootprint: 10.7,
    isEcoVerified: false,
    createdAt: new Date("2024-02-20"),
  },
]

// Calculate average carbon footprint for offers
export const averageCarbonFootprint = mockProducts.reduce((sum, p) => sum + p.carbonFootprint, 0) / mockProducts.length

// Mock admin user
export const mockAdmin = {
  id: "admin-1",
  email: "admin@dressstore.com",
  name: "Admin User",
  isAdmin: true,
}
